---
title: Creative Dump
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to my blog

'
    feature_image: ''
  uploads:
    title: Uploads
    output: true
remote_theme: daviddarnes/alembic
exclude:
- README.md
- Gemfile
- Gemfile.lock
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
url: https://mydomain.com
baseurl: ''
permalink: pretty
paginate: 5
paginate_path: blog/page:num
navigation_header:
- title: Contact
  url: "/contact/"
navigation_footer:
- title: Back to top
  url: "#top"
